### ISSUE TITLE
missing SAR metrics in README in staging

### ISSUE THREAD

**Issue by wutaomsft** [Microsoft/Recommenders#507] opened 2019-02-11 20:08 UTC
We no longer have SAR metrics in README.

**Comment by miguelgfierro** [comment] 2019-02-11 21:44
this is something that we are going to fix very soon with the new benchmarks we are doing, this is work in progress, but here https://github.com/Microsoft/Recommenders/blob/benchmark_feb/notebooks/03_evaluate/comparison_movielens.ipynb you can see that we are using the same dataset split to train all the algos. Before we were running the notebooks ,which didn't have the exact same dataset split

**Comment by miguelgfierro** [comment] 2019-04-12 06:37
duplicate of https://github.com/Microsoft/Recommenders/issues/464, being developed in PR https://github.com/Microsoft/Recommenders/pull/715

**Closed by miguelgfierro** 2019-04-12 06:37 UTC
Labels: high priority
