### ISSUE TITLE
Why databricks feedback CLIError:Please run 'az login' to setup account?

### ISSUE THREAD

**Issue by harbourlga** [Microsoft/Recommenders#500] opened 2019-02-11 08:34 UTC
client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB) 
above code feedback CLIError:Please run 'az login' to setup account,but in offline notebook jupyter is normal.
pleas help m, thanks!

**Comment by miguelgfierro** [comment] 2019-02-12 11:17
is this happening on Databricks?

**Comment by harbourlga** [comment] 2019-02-12 11:22
Yes,databricks

**Comment by dciborow** [comment] 2019-02-12 19:02
have you run the notebook from the top and logged in when starting the AML workspace? This assumes you have already logged in, in a previous step.

**Comment by harbourlga** [comment] 2019-02-13 03:48
i had try run  'az login'  on Cloud Shell ,   on databricks no solve

**Comment by nikhilrj** [comment] 2019-02-13 22:35
@harbourlga: try adding in a new cell in Databricks and do the following:

`%sh
pip install azure-cli
az login`

**Comment by harbourlga** [comment] 2019-02-14 02:00
thanks

**Comment by tengfei86** [comment] 2019-02-17 01:43
> client = get_client_from_cli_profile(azure.mgmt.cosmosdb.CosmosDB)
> above code feedback CLIError:Please run 'az login' to setup account,but in offline notebook jupyter is normal.
> pleas help m, thanks!

Did you solved the problem?

**Comment by jreynolds01** [comment] 2019-02-20 15:00
also see #529

**Comment by miguelgfierro** [comment] 2019-02-22 12:23
Closing this since the issue is solved. Feel free to reopen in case it is needed

**Closed by miguelgfierro** 2019-02-22 12:23 UTC

**Comment by IrtazaHaider12145** [comment] 2020-06-19 19:03
> @harbourlga the AML workspace creation code should give you a URL to authenticate your Azure account in the cell output - did you try restarting / rerunning the notebook? If that doesn't work, try adding in a new cell in Databricks and do the following to login manually:
> 
> ```
> %sh
> pip install azure-cli
> az login
> ```

Traceback (most recent call last):
  File "/databricks/python2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/databricks/python2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/databricks/python2/lib/python2.7/site-packages/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/databricks/python2/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 599, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/databricks/python2/lib/python2.7/site-packages/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/databricks/python2/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 425
    def cached_put(cmd_obj, operation, parameters, *args, setter_arg_name='parameters', **kwargs):
                                                                        ^
SyntaxError: invalid syntax


I am getting this error when I add this cell. The installation command works fine but all az commands give this error.
