### ISSUE TITLE
azureml_hyperdrive_surprise_svd notebook error

### ISSUE THREAD

**Issue by atimesastudios** [microsoft/recommenders#842] opened 2019-06-15 18:26 UTC
### Description
Notebook throws an error when submitting the experiment.

### In which platform does it happen?
System version: 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:18:50) [MSC v.1900 64 bit (AMD64)]
Surprise version: 1.0.6
Azure ML SDK Version: 1.0.39

### How do we replicate the issue?
pull from origin/master
run the python notebook

Problem occurs here:
# Create an experiment to track the runs in the workspace
exp = aml.core.Experiment(workspace=ws, name=EXP_NAME)
run = exp.submit(config=hd_config)

azureml.widgets.RunDetails(run).show()
run.wait_for_completion(show_output=True)

Output is:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-5a56dcc735be> in <module>
      1 # Create an experiment to track the runs in the workspace
      2 exp = aml.core.Experiment(workspace=ws, name=EXP_NAME)
----> 3 run = exp.submit(config=hd_config)
      4 
      5 azureml.widgets.RunDetails(run).show()

~\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\azureml\core\experiment.py in submit(self, config, tags, **kwargs)
    142         submit_func = get_experiment_submit(config)
    143         with self._log_context("submit config {}".format(config.__class__.__name__)):
--> 144             run = submit_func(config, self.workspace, self.name, **kwargs)
    145         if tags is not None:
    146             run.set_tags(tags)

~\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\azureml\train\hyperdrive\_search.py in search(hyperdrive_run_config, workspace, experiment_name)
    100 
    101         experiment_dto = _create_experiment_dto(hyperdrive_run_config, workspace, experiment_name,
--> 102                                                 telemetry_values, activity_logger)
    103 
    104         try:

~\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\azureml\train\hyperdrive\_search.py in _create_experiment_dto(hyperdrive_run_config, workspace, experiment_name, telemetry_values, activity_logger)
     30         activity_logger.info("Creating snapshot...")
     31 
---> 32     platform_config = hyperdrive_run_config._get_platform_config(workspace, experiment_name)
     33     # source_directory might be None if this run is a hydrate from cloud.
     34     if hyperdrive_run_config.source_directory is not None:

~\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\azureml\train\hyperdrive\runconfig.py in _get_platform_config(self, workspace, run_name)
    301         run_config = self._remove_duplicate_arguments(run_config,
    302                                                       self._generator_config,
--> 303                                                       self.estimator is not None)
    304 
    305         project_context = self._get_project_context(workspace, run_name)

~\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\azureml\train\hyperdrive\runconfig.py in _remove_duplicate_arguments(run_config, generator_config, is_estimator)
    358                 # Add lstrip: The run_config script param input expects the -- to be specified for script_params.
    359                 # In HyperDrive, parameter space, user doesn't specify hyphens in the beginning of the parameter.
--> 360                 if param.lstrip("-") in parameter_space:
    361                     run_config_args.pop(param)
    362                     warning = True

AttributeError: 'int' object has no attribute 'lstrip'

**Comment by atimesastudios** [comment] 2019-06-15 18:29
[myenv.zip](https://github.com/microsoft/recommenders/files/3293418/myenv.zip)

**Comment by yueguoguo** [comment] 2019-06-16 08:05
Thanks @atimesastudios the issue is known after the recent update of AzureML Python SDK - that is, the `script_params` parameter of estimator should be string typed. The PR by @chenhuims in #840 is to fix the issue.

**Comment by atimesastudios** [comment] 2019-06-16 18:48
Thank you @yueguoguo and @chenhuims.

**Comment by loomlike** [comment] 2019-07-09 14:19
This issue has been resolved by #840 and #847. Thanks!

**Closed by loomlike** 2019-07-09 14:19 UTC
