### ISSUE TITLE
Investigate difference between new and 0.1.1 SAR versions when using movielens 10M

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/Recommenders#465] opened 2019-01-30 10:54 UTC
### *What* is affected by this bug?
In the SAR quickstart notebook, when using movielens 10M, there is a significat difference in the metrics and in the compute time

For SAR in release 0.1.1, the metrics are:
```
Took 109.8672547340393 seconds for training.
Took 9.996008157730103 seconds for prediction.
Model:	sar_ref
Top K:	10
MAP:	0.101402
NDCG:	0.321073
Precision@K:	0.275766
Recall@K:	0.156483
```
The new SAR in staging:
```
Took 563.519758939743 seconds for training.
Took 8.40031886100769 seconds for prediction.
Model:	sar_ref
Top K:	10
MAP:	0.066775
NDCG:	0.249102
Precision@K:	0.216268
Recall@K:	0.106777
```

### In *which* platform does it happen?
* *Azure Data Science Virtual Machine.*

Steps for both versions:
- [ ] Check the results with 100k, 1M and 20M
- [x] Check that the unit tests are passing

**Comment by miguelgfierro** [comment] 2019-01-30 11:02
Results of new and old SAR with **ML1M**
For SAR in release 0.1.1, the metrics are:
```
Took 9.09568476676941 seconds for training.
Took 0.3207972049713135 seconds for prediction.
Model:	sar_ref
Top K:	10
MAP:	0.064013
NDCG:	0.308012
Precision@K:	0.277215
Recall@K:	0.109292
```

The new SAR in staging:
```
Took 5.787659168243408 seconds for training.
Took 0.4074389934539795 seconds for prediction.
Model:	sar_ref
Top K:	10
MAP:	0.064013
NDCG:	0.308012
Precision@K:	0.277215
Recall@K:	0.109292
```

**Comment by gramhagen** [comment] 2019-01-31 00:07
just confirming that we see the same results despite changes to the notebook.
I took a python export of the notebook in staging and modified it to run through all the data set sizes then ran it on current staging as well as release 0.1.1 and the results match what you get. So it's definitely a change in the code itself. I'll look a bit closer on what has changed in the sar model.

**Comment by gramhagen** [comment] 2019-01-31 03:09
line profiling the two version of the fit() method reveals a difference in the dot() calculation

| Version | Line | Time (us) | Time (%) | Line Contents |
|----------|-----|------------|-----------|----------------|
| Staging | 403 | 582523501.0 | 92.0 | self.scores = self.user_affinity.dot(self.item_similarity) |
| Master | 380 | 69671170.0 | 56.7 |  self.scores = self.user_affinity.dot(self.item_similarity) |

barring the possibility that the actually matrices are not equivalent across versions (which seems unlikely as the 100k and 1m datasets produce the same results I expect the issue is due to something numpy is doing under the hood.

see the answer here: https://stackoverflow.com/questions/19839539/how-to-get-faster-code-than-numpy-dot-for-matrix-multiplication

it's possible that something with the datatypes changed which is preventing numpy from calling the BLAS library, though I wouldn't expect there to be significant differences in the final matrix? maybe it's only realized when the small differences are summed up across a large number of items.

next step is just to confirm the user_affinity and item_similarity matrices are identical across versions and check the datatypes and numpy flags, then maybe try gemm directly.

**Comment by gramhagen** [comment] 2019-01-31 18:22
Right, @anargyri as you mentioned the item_similarity object type changed from a numpy matrix to scipy sparse csc matrix, apparently the using the dot function on that is much slower than a dense matrix.

But the good news is it's quite easy to convert it back to dense before passing it into the dot function. I tested that and it seems to resolve the speed issue. I am testing now to see how that change impacts the results.

**Comment by anargyri** [comment] 2019-01-31 19:08
Also the efficiency of `dot()` depends on the types of sparse matrices. I haven't found a recommendation in scipy about this, so I chose user_affinity to be csr and item_similarity to be csc. 
It is probably important that item_similarity is not really sparse (maybe ~50% or so), so maybe there are no advantages in sparse multiplication (on that line; the products before that should benefit from sparse matrix types).
Does the dense matrix come at a cost of more memory?

**Comment by gramhagen** [comment] 2019-01-31 19:46
it doesn't seem like we're saving much memory by using the sparse matrix, here's plots of memory usage over time (for the fit method on 10m dataset).

<b>Current Staging</b>
![master_mprof](https://user-images.githubusercontent.com/5720537/52080567-1aead400-2566-11e9-8ba1-82ae64c1414c.jpg)

<b>Current Master</b>
![staging_mprof](https://user-images.githubusercontent.com/5720537/52080577-1faf8800-2566-11e9-9a5c-497c32bf7887.jpg)

So we get ~ 15% reduction in memory.

**Comment by gramhagen** [comment] 2019-01-31 19:49
Here are the results from speed / eval standpoint. In the 'fix' version I just change the final calculation in fit() to be: ```self.scores = self.user_affinity.dot(self.item_similarity.todense())```

You can see the 'fix' version is still slightly slower than 0.1.1, and the performance is degraded, but I think this is just due to using single vs double floating point precision.

Version | dataset | fit (s) | map | ndcg | precision@10 | recall@10
-- | -- | -- | -- | -- | -- | --
SAR 0.1.1 | ml 100k | 0.5262 | 0.105815 | 0.37319 | 0.326617 | 0.175957
SAR Staging | ml 100k | 0.6034 | 0.105815 | 0.373197 | 0.326617 | 0.175957
SAR Staging Fix | ml 100k | 0.4761 | 0.105815 | 0.373197 | 0.326617 | 0.175957
SAR 0.1.1 | ml 1m | 6.2893 | 0.064013 | 0.308012 | 0.277215 | 0.109292
SAR Staging | ml 1m | 9.9825 | 0.064013 | 0.308012 | 0.277215 | 0.109292
SAR Staging Fix | ml 1m | 5.3546 | 0.064013 | 0.308012 | 0.277215 | 0.109292
SAR 0.1.1 | ml 10m | 132.1281 | 0.101402 | 0.321073 | 0.275766 | 0.156483
SAR Staging | ml 10m | 619.7484183 | 0.066775 | 0.249102 | 0.216268 | 0.106777
SAR Staging Fix | ml 10m | 212.5266 | 0.066775 | 0.249102 | 0.216268 | 0.106777

**Comment by gramhagen** [comment] 2019-01-31 21:18
Thoughts on this? I can certainly update the line of code and 'correct' the test metrics. But just want to make sure others are ok with that approach

**Comment by miguelgfierro** [comment] 2019-02-01 09:14
this is great, I think the issue with the speed is solved by the dense multiplication. However, there is still the issue with the performance. It is super odd that 100k and 1M provide the exact same results and 10M (and I guess 20M) provide a different one. In SAR there should not be difference in the results across runs, since the algo is deterministic.

@gramhagen can you check this?

>  the performance is degraded, but I think this is just due to using single vs double floating point precision.

Another question, the results you are showing in the table are float32 or float64?

**Comment by anargyri** [comment] 2019-02-01 11:11
Nice plots! Good catch about the time efficiency. Since `item_similarity` is not really sparse, it makes sense; let's keep the change you made.
Regarding the metrics, it is unlikely that the discrepancies are due to this line of code. It would also be strange were it due to precision: when the data set increases by a factor of 10 we get from 6 decimal digits match to 1 decimal. 
I suspect the discrepancy is due to something else. One thing that might help is to locate the first commit that modified this function in which the discrepancy appears.

**Comment by gramhagen** [comment] 2019-02-01 14:19
Results above are from 0.1.1 using float64 while staging uses float32
I agree it's quite strange to see such a dramatic change just from switching the precision only on larger datasets, I'll do some more digging to get to the bottom

**Comment by gramhagen** [comment] 2019-02-05 01:45
stalled a bit on this because after staring at the code for so long I was compelled to clean it up, anyway the issue is resolved and from what I can tell derived from numpy doing something funky when applying the dot product across a csr and csc matrix. The changes to jaccard and lift slowed down the computation a bit, so I reverted them and silenced the divide by zero warnings (the result is still correct regardless), there's a few more changes, but the metrics are back on track as well as the speed so I think we're in good shape, I'll push a PR shortly

**Comment by miguelgfierro** [comment] 2019-02-07 11:59
hey @gramhagen is this issue solved on the PR you are working on?

**Comment by gramhagen** [comment] 2019-02-08 14:16
Closing this now that #485 is merged

**Closed by gramhagen** 2019-02-08 14:16 UTC
Labels: algorithm, bug, notebook, test
