### ISSUE TITLE
AttributeError: module 'papermill' has no attribute 'record'

### ISSUE THREAD

**Issue by faizan1990** [microsoft/recommenders#1195] opened 2020-08-31 02:31 UTC
### Description
[Baseline Deep Dive](https://github.com/microsoft/recommenders/blob/master/examples/02_model_collaborative_filtering/baseline_deep_dive.ipynb) is using `papermill`'s attribute: `record`

Unfortunately, `record` attribute was removed from `papermill` as per:
https://github.com/nteract/papermill/issues/507

Please update the code accordingly!

Thanks.

**Comment by gramhagen** [comment] 2020-08-31 12:46
this is a duplicate of #641 currently the papermill version is pinned here: https://github.com/microsoft/recommenders/blob/837b8081a4421e144f2bc05ba949c5ac6c52320f/tools/generate_conda_file.py#L60

but we are certainly open to updating the notebooks to use scrapbook and then upgrading papermill version. if you have some time to help out PRs are welcome.

in the meantime you can downgrade the version of papermill you are using to match.

thanks, closing this for now

**Closed by gramhagen** 2020-08-31 12:46 UTC
