### ISSUE TITLE
[ASK] Can not download nrms.zip

### ISSUE THREAD

**Issue by SuJiaKuan** [microsoft/recommenders#1151] opened 2020-07-20 09:23 UTC
### Description

When I run the news recommendation by [nrms](https://github.com/microsoft/recommenders/blob/08e0b204265f9084baf000c816d377827b104dfe/examples/00_quick_start/nrms_synthetic.ipynb), the following error occurs:

```
Traceback (most recent call last):
  File "nrms.py", line 56, in <module>
    main()
  File "nrms.py", line 26, in main
    download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/newsrec/', data_path, 'nrms.zip')
  File "/home/feabries/projects/Recommenders/reco_utils/recommender/deeprec/deeprec_utils.py", line 497, in download_deeprec_resources
    zip_ref = zipfile.ZipFile(os.path.join(data_path, remote_resource_name), "r")
  File "/home/feabries/anaconda3/envs/tf_v2/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/feabries/anaconda3/envs/tf_v2/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

It seems that https://recodatasets.blob.core.windows.net/newsrec/nrms.zip does not exist, so the process can not download the zip file and the error occurs.

![Screenshot_20200720_172302](https://user-images.githubusercontent.com/12513248/87921850-b733ce00-caad-11ea-9afb-c7ce53e3bf6d.png)

Anyone knows what's is the correct link to `nrms.zip`?

**Comment by miguelgfierro** [comment] 2020-07-20 09:55
duplicate of https://github.com/microsoft/recommenders/issues/1150

**Closed by miguelgfierro** 2020-07-20 09:55 UTC
Labels: duplicate, help wanted
